### ISSUE TITLE
README: run_mode flag appears to be obsolete

### ISSUE THREAD

**Issue by jogaco** [steverice/pt-osc#8]
From source code, this flag seems to be execute now, with values true, false.

**Comment by steverice** [comment]
@jogaco [`run_mode`](https://github.com/steverice/pt-osc/blob/3a6a4006122167de4ca1405b1729ae533fbc4877/lib/active_record/pt_osc_migration.rb#L44-L45) still controls [whether the command will be printed or run by `pt-online-schema-change`](https://github.com/steverice/pt-osc/blob/3a6a4006122167de4ca1405b1729ae533fbc4877/lib/active_record/pt_osc_migration.rb#L77-L80), as stated in the README.
The `execute` flag seen in source controls [whether `pt-online-schema-change` is passed the `--dry-run` or `--execute` flag](https://github.com/steverice/pt-osc/blob/3a6a4006122167de4ca1405b1729ae533fbc4877/lib/active_record/pt_osc_migration.rb#L226).

It's a bit of an unfortunate naming collision — I'll look to change that in a future refactor :grin:

**Comment by jogaco** [comment]
Something related to this is not working smoothly.
When I use:

```
  percona:
    run_mode: execute
    defaults-file: /etc/mysql/percona-user.cnf
    username: root
    execute: true
    log: ./log/pt-schema.log
```
I get:

```
Segmentation fault (core dumped)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
```

If I remove
```
    execute: true
```
All works well, even though pt-online-schema-change prints this message:
```
Starting a dry run.  `mydatabase`.`mytable` will not be altered.  Specify --execute instead of --dry-run to alter the table.
```
But the changes are there after finishing the rake task.
Maybe something odd with ptosc ? Using 2.2.14.

**Comment by steverice** [comment]
Could be a pt-osc issue. What are the contents of your `pt-schema.log`? You may also want to copy the command from there and [run it with a debug flag](https://bugs.launchpad.net/percona-toolkit/+bug/1367233/comments/4) to get more info.
